version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    command: -c 'max_connections=2000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"